ID_NOT_INT = 'Id should be an integer' # pragma: no mutate
ID_NONE_WHEN_ADD = 'Id should be none when adding a product' # pragma: no mutate
QUANTITY_NOT_INT = 'Quantity should be an integer' # pragma: no mutate
QUANTITY_LOWER_THAN_ONE = 'Quantity is lower than 1' # pragma: no mutate
NAME_NOT_STRING = 'Name should be a string' # pragma: no mutate
NAME_CONFLICT = 'This name is already used by another product' # pragma: no mutate
PRODUCT_NOT_FOUND = 'This product does not exist' # pragma: no mutate
MISSING_ARGUMENTS = 'Missing arguments' # pragma: no mutate
INTERNAL_ERROR = 'Internal server error, please try again later' # pragma: no mutate
